### ISSUE TITLE
Indentation is broken at ${} in the template literal

### ISSUE THREAD

**Issue by lazex** [dprint/dprint-plugin-typescript#455] opened 2022-11-25 16:06 UTC
**Describe the bug**

dprint-plugin-typescript version: 0.78.0

**Input Code**

```ts
{
    {
        const x = `
            aaa
            ${
                aaaaaaaaaaa
                    ? "aaaaaaaaaaaaaaaaaaaaaaaaaaa"
                    : "bbbbbbbbbbbbbbbbbbbbbbbbbbb"
            }
            bbb
        `;
    }
}
```

**Expected Output**

```ts
{
    {
        const x = `
            aaa
            ${
                aaaaaaaaaaa
                    ? "aaaaaaaaaaaaaaaaaaaaaaaaaaa"
                    : "bbbbbbbbbbbbbbbbbbbbbbbbbbb"
            }
            bbb
        `;
    }
}
```

**Actual Output**

```ts
{
    {
        const x = `
            aaa
            ${
            aaaaaaaaaaa
                ? "aaaaaaaaaaaaaaaaaaaaaaaaaaa"
                : "bbbbbbbbbbbbbbbbbbbbbbbbbbb"
        }
            bbb
        `;
    }
}
```

https://dprint.dev/playground/#code/N4WAUABFGp3wYwPYDsDOAXCAPCBeCAA3HlOgENKSzSASWGxiSl1quJpgfggCI2BgoeV7VOjAFx8ARrLnyFixaI5MAvmKZzN8QgG5NGsGqA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kAA4AnRCMTbIUyAEc2ijIgDKGAJ7REwyOIDuvWxwAiitvwdHyU3NLAAVtRU11KB1ELm0AN0djJBcAGQREAGlKJ2gRANZORAAhbV4AY1inFyxqADkLKwQAcwd0pAKofjLKkMUOWAxYVScOXhlEdsQAVXgHDg4ACV54ZpbOyAHVh2LFNFs+gaGRjRleBAxz+A2kAA8MJRpw6AAxFRdDweHrjTGJqY2GDKsDgqyUMjOUUgqmgtgAsmxoEMAcYIgZeBhFNpPscflA7hgUYEYvptMtVut8GIJIhjCSDE1tpMMsJqZJArxtOEXC82PByriAHRFEKc6jYWJVU5XS4IDb8BCc2wAUVuMQW30FoMQIQMqvVAxOonE7NYACsOLdBd0KgBrRAYHHfJwEonmy2CkRYyp1RBpDIcKxsLk+eBoFqPSw0Vkm2mBC1WswWax2fwaenaby+fzGBOCmSI5EZUW6NRODMbCYyfh6tW6DWqLXF2sG51U2PGOyaZmWMrQQVcTScjFY7Jh0aIORKFTXYzUNgyTyIcrQYdCqs17RWIflSlQM4XK4bDg7xAAQXCfLQMZpxhPFWswcvYZaYTR2iGUrAQLYcdYin4M1lwwfV60NeAB1PIMQyvV9wm7D9YC-H8-ygACgIFUUMF7CD70qaDn3DVY3wQz8ohQztbG7dJe3ESCHwI0MiOaEiDDI4QKMCBV4CVUDYnA+j8KfJiWmKQYXFgLgzzDC9BiwCYhnKAB5BCR0MfBONYcpFAhcUpk9b1rFPM8RF7KxVw4WpyO0X9jG0tQfwFLFBJKPQsR1MUaCsr82VQyB7I4RzMW0bgqMQFyTN7X0XEyRBbBcLFr3bW9AgCoKmmaHiMGDcK8PPUyDGi2L4sSm9TSgNBFGQLAQRTDFJ3FCKCu0arauKhLtCS78bL8xA1SxDAlxXNdNTyxjYNWOpxkQNB9QG6zbMCL1tAASXgGx6omGgmt7F5Rzijqus0qBlqUkQNssLaMB2gw9u0drSo0nrjGWi6Gu2vLItu-aSs6jjnqWrE3qum6t0nBRlFUBa-JEPkBW+IbVzKIU8uKNzdBLcVvKiXyXrh3E+IbXDTzR5aPNLCUuBxjslvx75CYEz7mt5flcQev7kvKyBmgdM9ykqBZnNR9HyaxyVqZS1hYHOy5LsapnexWkR2aOgGpZkTQBsRkbGzG4SJuaKaJjQFaNfm-7FvdW4rEQPJ5BULZmmVBwQeFsnzN4SyLb8hMGe+SMrgMFzxpfVY-aNXHAgUrA9hc0n3MxrzxbKvyuAwPmBY4IWSZFxPKZ8mnWEuZoebQbhJ00VdLDjkWaPRaAU8o7tpPgCwMVGnOyenCPC6gLtzwWNiO4fePdHDvFjsgGpauB+XjOa1qHBV73jFgTL3IaKhwSu8v7icNAdAuABaNfW90DZT-cl5au38Vd4wffD5oE-190I+RFqyAQAAXxAIA/language/typescript

**Comment by dsherret** [comment] 2022-11-29 23:50
This is a duplicate of #349.

The reason it occurs is because the indentation occurs from where the last declaration is and not where the `${` happens to be. It should probably be changed to take the `${` into consideration though.

**Closed by dsherret** 2022-11-29 23:50 UTC
